[package]
name = "dealer-eval"
version = "1.0.0"
edition = "2021"
license = "Unlicense"

[dependencies]
dealer-core = { path = "../dealer-core" }
dealer-parser = { path = "../dealer-parser" }
dealer-dds = { path = "../dealer-dds" }
rustc-hash = "2.0"

[dev-dependencies]
dealer-pbn = { path = "../dealer-pbn" }
