//! Levelling a scenario: measuring how often each hand type comes up, working
//! out the keep rate for each, and writing the result back into the script.
//!
//! Lifted out of the command-line tool so the browser build can level too. What
//! is here is everything that does not need to deal a card — the arithmetic and
//! the text — while the measuring itself belongs to whichever front end is
//! running the deals.
//!
//! `docs/leveling-strategy.md` is the method, with the numbers behind it.

use dealer_parser::{Expr, Program, Statement};

/// A scenario ready to receive a levelling block, writing one in if it has none.
///
/// The placeholder is a convenience for a script written to be levelled, not a
/// requirement. A script that names its hand types has already said everything
/// the levelling needs to know, so asking it to also carry three lines of
/// boilerplate is asking twice. When they are missing they are written in: the
/// block just above the condition, where it reads, and `and levelTheDeal` on
/// the end of the condition itself.
///
/// The condition is the one part that cannot be guessed, since the original's
/// grammar lets it be a bare expression and half the scenarios in the wild
/// write it that way. So it is found with the parser rather than by hunting for
/// a keyword.
pub fn insert_leveling_block(source: &str) -> Result<String, String> {
    if source.contains(LEVEL_BEGIN) {
        return Ok(source.to_string());
    }
    let span = dealer_parser::condition_span(source).ok_or_else(|| {
        "the scenario has no condition, so there is nothing for the levelling to \
         gate.\n       Add one, or a `### BEGIN GENERATED LEVELING ###` placeholder saying \
         where the block belongs."
            .to_string()
    })?;
    // The line the *statement* begins on, not the expression's. `condition`
    // alone on a line with its expression on the next is common in the wild,
    // and inserting at the expression's line would put the block between the
    // two — leaving the keyword to read `noLeveling` as its condition and fail
    // on the `= 1` after it.
    let line_start = source[..span.statement].rfind('\n').map_or(0, |i| i + 1);
    let end = span.end;

    let block = format!(
        "{LEVEL_BEGIN}\n# Written in because the scenario named hand types and left no \
         placeholder.\nnoLeveling = 1\nlevelTheDeal = noLeveling\n{LEVEL_END}\n\n"
    );
    // A scenario may already gate on the verdict without having marked where the
    // block goes, in which case the condition is left alone.
    let gate = if source.contains("levelTheDeal") || source.contains("keepTheDeal") {
        ""
    } else {
        " and levelTheDeal"
    };
    Ok(format!(
        "{}{}{}{}{}",
        &source[..line_start],
        block,
        &source[line_start..end],
        gate,
        &source[end..]
    ))
}

/// Check a scenario can take a generated levelling block, before anything is
/// dealt. Returns the verdict variable's name and the scale of any `roll` it
/// already defines.
///
/// Up front rather than at the end: measuring is a hundred thousand deals, and
/// none of it is worth doing if the file cannot receive the answer.
pub fn check_leveling_source(source: &str) -> Result<(&'static str, Option<u32>), String> {
    if source.contains(LEVEL_STAMP) {
        return Err(
            "this scenario was generated by --write-leveled, not written by hand.\n       \
             Levelling it again would measure the already-levelled mix, compute keeps of \
             roughly 1,\n       and quietly write a scenario with no levelling at all. Use \
             the stock file."
                .to_string(),
        );
    }
    let (head, rest) = source.split_once(LEVEL_BEGIN).ok_or_else(|| {
        format!(
            "the scenario needs a placeholder for the generated levelling:\n    {}\n    \
             noLeveling = 1\n    levelTheDeal = noLeveling\n    {}",
            LEVEL_BEGIN, LEVEL_END
        )
    })?;
    let (_, tail) = rest
        .split_once(LEVEL_END)
        .ok_or_else(|| format!("the scenario has {} but no {}", LEVEL_BEGIN, LEVEL_END))?;

    // Whichever name the scenario already uses for the verdict.
    let verdict = ["levelTheDeal", "keepTheDeal"]
        .into_iter()
        .find(|name| tail.contains(name))
        .ok_or_else(|| {
            "nothing after the generated block uses `levelTheDeal`, so the levelling would \
             have no effect. Add it to the condition."
                .to_string()
        })?;
    let roll_scale = existing_roll(&format!("{}{}", head, tail))?;
    Ok((verdict, roll_scale))
}

/// `source` with its levelling block filled in.
///
/// The text it returns is the scenario itself, not a report: how a run reads on
/// a terminal is the caller's business, and baking a column layout in here would
/// have the browser throwing away a string it never wanted.
///
/// Everything it refuses is a way the method goes quietly wrong: a generated
/// file fed back in would measure the already-levelled mix and compute keeps of
/// roughly 1, writing a scenario with no levelling at all and a stamp that
/// agrees with itself.
#[allow(clippy::too_many_arguments)]
pub fn render_leveled(
    source: &str,
    plans: &[LevelPlan],
    lambda: f64,
    acceptance: f64,
    base_rate: f64,
    measured: usize,
    seed: u32,
    prefix: &str,
    groups: &[(String, f64)],
) -> Result<String, String> {
    if source.contains(LEVEL_STAMP) {
        return Err(
            "this scenario was generated by --write-leveled, not written by hand.\n       \
             Levelling it again would measure the already-levelled mix, compute keeps of \
             roughly 1,\n       and quietly write a scenario with no levelling at all. Use \
             the stock file."
                .to_string(),
        );
    }
    let (head, rest) = source.split_once(LEVEL_BEGIN).ok_or_else(|| {
        format!(
            "the scenario needs a placeholder for the generated levelling:\n    {}\n    \
             noLeveling = 1\n    levelTheDeal = noLeveling\n    {}",
            LEVEL_BEGIN, LEVEL_END
        )
    })?;
    let (_, tail) = rest
        .split_once(LEVEL_END)
        .ok_or_else(|| format!("the scenario has {} but no {}", LEVEL_BEGIN, LEVEL_END))?;

    // Whichever name the scenario already uses for the verdict.
    let verdict = ["levelTheDeal", "keepTheDeal"]
        .into_iter()
        .find(|name| tail.contains(name))
        .ok_or_else(|| {
            "nothing after the generated block uses `levelTheDeal`, so the levelling would \
             have no effect. Add it to the condition."
                .to_string()
        })?;

    let outside = format!("{}{}", head, tail);
    let roll_scale = existing_roll(&outside)?;
    let scale = roll_scale.unwrap_or(1000);

    let width = plans.iter().map(|p| p.name.len()).max().unwrap_or(0).max(4);
    let mut block = vec![
        LEVEL_BEGIN.to_string(),
        format!("{}. Do not edit; edit the stock", LEVEL_STAMP),
        "# scenario and regenerate, or the two will disagree without saying so.".to_string(),
        "#".to_string(),
        format!("# measured over  {} deals, seed {}", measured, seed),
        "#".to_string(),
        format!(
            "# {:<width$}  {:>9} {:>9} {:>8} {:>9}",
            "type",
            "natural",
            "target",
            "keep",
            "seen",
            width = width
        ),
    ];
    for plan in plans {
        block.push(format!(
            "# {:<width$}  {:>9.5} {:>9.5} {:>8.4} {:>9}",
            plan.name,
            plan.natural,
            plan.target,
            plan.keep,
            plan.seen,
            width = width
        ));
    }
    let rarest = plans
        .iter()
        .min_by(|a, b| a.natural.total_cmp(&b.natural))
        .expect("at least one hand type");
    let relative = if rarest.seen > 0 {
        (rarest.natural * (1.0 - rarest.natural) / measured as f64).sqrt() / rarest.natural
    } else {
        f64::INFINITY
    };
    block.extend([
        "#".to_string(),
        format!(
            "# exactness      {:.3}{}",
            lambda,
            if lambda >= 0.999 {
                "  (full)"
            } else {
                "  (relaxed to fit the budget)"
            }
        ),
        format!("# acceptance     {:.4} of qualifying deals", acceptance),
        format!(
            "# cost           about {:.0} deals dealt per deal kept",
            1.0 / (base_rate * acceptance)
        ),
        format!(
            "# precision      keeps set by {}, the rarest, seen {} times (+-{:.1}%); expect \
             the mix within +-{:.2} points",
            rarest.name,
            rarest.seen,
            100.0 * relative,
            100.0 * rarest.mix * relative
        ),
        String::new(),
    ]);
    if roll_scale.is_some() {
        block.push(format!(
            "# `roll` comes from the scenario, drawing over 0..{}.",
            scale - 1
        ));
    } else {
        block.push(canonical_roll(scale));
    }
    block.push(String::new());
    for plan in plans {
        let keep = (plan.keep * scale as f64).round() as u32;
        if plan.keep <= 0.0 {
            // A weight of zero asks for none of this type, and `roll < 0`
            // reads as a mistake. Rounding up to one in `scale` instead would
            // deliver a share the header beside it says is nothing.
            block.push(format!("level_{} = 0", plan.name));
        } else if keep == 0 {
            // Under half of one in `scale`, so no threshold expresses it. The
            // header would go on claiming the mix while the file delivered
            // either nothing or twice what was asked, depending on which way
            // it was rounded.
            return Err(format!(
                "`{}` wants to be kept {:.6} of the time, which is less than one deal in \
                 {}.\n       No threshold on this roll says that. Give `{}` more of the \
                 target, or define\n       a finer roll before the block: {}",
                plan.name,
                plan.keep,
                scale,
                plan.name,
                canonical_roll(scale.saturating_mul(100).max(scale))
            ));
        } else if keep >= scale {
            block.push(format!("level_{0} = {1}_{0}", plan.name, prefix));
        } else {
            block.push(format!(
                "level_{0} = {1}_{0} and roll < {2}",
                plan.name, prefix, keep
            ));
        }
    }
    block.push(format!(
        "{} = {}",
        verdict,
        plans
            .iter()
            .map(|p| format!("level_{}", p.name))
            .collect::<Vec<_>>()
            .join(" or ")
    ));
    block.push(LEVEL_END.to_string());

    let generated = format!("{}{}{}", head, block.join("\n"), tail);
    let generated = fill_mix_markers(&generated, plans, groups)?;

    Ok(generated)
}

/// `render_leveled`, then put it in a file.
///
/// The rendering is separate because the browser build levels too and has
/// nowhere to write; there the generated scenario is shown rather than saved.
#[allow(clippy::too_many_arguments)]
pub fn write_leveled(
    source: &str,
    path: &std::path::Path,
    plans: &[LevelPlan],
    lambda: f64,
    acceptance: f64,
    base_rate: f64,
    measured: usize,
    seed: u32,
    prefix: &str,
    groups: &[(String, f64)],
) -> Result<String, String> {
    let generated = render_leveled(
        source, plans, lambda, acceptance, base_rate, measured, seed, prefix, groups,
    )?;
    std::fs::write(path, &generated)
        .map_err(|e| format!("could not write {}: {}", path.display(), e))?;
    Ok(generated)
}

/// The markers a stock scenario leaves for the generated levelling.
pub const LEVEL_BEGIN: &str = "### BEGIN GENERATED LEVELING ###";
pub const LEVEL_END: &str = "### END GENERATED LEVELING ###";
/// Written into every generated file, so one fed back in is recognised.
pub const LEVEL_STAMP: &str = "# Generated by dealer --write-leveled";

/// Whether a scenario already defines `roll`, and over what range.
///
/// A scenario may get `roll` from an include, and writing a second definition
/// would be noise at best. So an existing one is used as it stands — but only
/// in the shape the keeps assume, a uniform draw over `0..scale-1` on every
/// build. `rnd(N)` on its own is not that: a locally built dealer returns
/// values outside the bound, or negative ones.
pub fn existing_roll(text: &str) -> Result<Option<u32>, String> {
    let assignments: Vec<&str> = text
        .lines()
        .filter(|line| {
            let trimmed = line.trim_start();
            trimmed.starts_with("roll") && trimmed[4..].trim_start().starts_with('=')
        })
        .collect();
    match assignments.len() {
        0 => return Ok(None),
        1 => {}
        n => {
            return Err(format!(
                "`roll` is assigned {} times outside the generated block. Leave exactly one.",
                n
            ))
        }
    }
    let line = assignments[0].trim();
    let numbers: Vec<u32> = line
        .split(|c: char| !c.is_ascii_digit())
        .filter(|piece| !piece.is_empty())
        .filter_map(|piece| piece.parse().ok())
        .collect();
    let canonical = numbers
        .first()
        .map(|n| canonical_roll(*n))
        .unwrap_or_default();
    if numbers.len() == 4 && numbers.iter().all(|n| n == &numbers[0]) && line == canonical {
        Ok(Some(numbers[0]))
    } else {
        Err(format!(
            "`roll` is already defined, but not in the form the keeps assume:\n    \
             found     {}\n    expected  roll = (rnd(N) % N + N) % N\n       The double \
             modulo is what makes the draw uniform on every build; without it a locally \
             built dealer returns values outside the bound, or negative ones.",
            line
        ))
    }
}

pub fn canonical_roll(scale: u32) -> String {
    format!("roll = (rnd({0}) % {0} + {0}) % {0}", scale)
}

/// Fill `{{level-mix:type}}` and `{{level-mix}}` from the mix that was chosen.
///
/// The player-facing text is written by hand and drifts: one scenario in the
/// corpus advertised 23% for a band delivering 19.3%. Filling it from the same
/// numbers as the keeps is the only way the two cannot disagree.
pub fn fill_mix_markers(
    text: &str,
    plans: &[LevelPlan],
    groups: &[(String, f64)],
) -> Result<String, String> {
    let percent = |mix: f64| {
        let value = 100.0 * mix;
        if (value - value.round()).abs() < 0.05 {
            format!("{:.0}%", value)
        } else {
            format!("{:.1}%", value)
        }
    };

    // What a marker may name. The presentation groups come first where they
    // exist, because the text a student reads is written about those — a
    // scenario levelling on `LevelType_12` still says "12-14 HCP" in its chat
    // block. Where there are none, the levelled types are the groups.
    let known: Vec<(String, f64)> = if groups.is_empty() {
        plans.iter().map(|p| (p.name.clone(), p.mix)).collect()
    } else {
        groups.to_vec()
    };

    let width = known.iter().map(|(n, _)| n.len()).max().unwrap_or(0);
    let all: String = known
        .iter()
        .map(|(n, mix)| format!("{:<width$}  {}", n, percent(*mix), width = width))
        .collect::<Vec<_>>()
        .join("\n");

    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(start) = rest.find("{{level-mix") {
        out.push_str(&rest[..start]);
        let tail = &rest[start..];
        let end = tail
            .find("}}")
            .ok_or_else(|| "a `{{level-mix` marker is never closed".to_string())?;
        let inside = &tail[2..end];
        let named = inside.strip_prefix("level-mix:").map(str::trim);
        match named {
            None => out.push_str(&all),
            Some(name) => match known.iter().find(|(n, _)| n == name) {
                Some((_, mix)) => out.push_str(&percent(*mix)),
                None => {
                    return Err(format!(
                        "`{{{{level-mix:{}}}}}` names a category the scenario does not \
                         declare. Known: {}",
                        name,
                        known
                            .iter()
                            .map(|(n, _)| n.as_str())
                            .collect::<Vec<_>>()
                            .join(", ")
                    ))
                }
            },
        }
        rest = &tail[end + 2..];
    }
    out.push_str(rest);
    Ok(out)
}

/// How many produced deals it would take for the rarest type to be seen
/// `goal` times, judged from what has been seen so far.
///
/// The measuring pass is sized by the rarest type and nothing else, because the
/// keep is `mix / natural` and it is that divisor's relative error that ends up
/// in the delivered mix. A type at 0.2% of qualifying deals needs a quarter of
/// a million produced to be seen 500 times; one at 5% needs ten thousand. No
/// single fixed number serves both, which is why this is worked out rather than
/// chosen.
///
/// Returns 0 when nothing has been seen yet, which is the caller's signal that
/// the probe was too small to estimate from at all.
pub fn needed_produce(counts: &[usize], produced: usize, goal: usize) -> usize {
    let rarest = counts.iter().copied().min().unwrap_or(0);
    if rarest == 0 || produced == 0 {
        return 0;
    }
    // Round up: asking for exactly the goal lands short half the time.
    (goal as f64 * produced as f64 / rarest as f64).ceil() as usize
}

/// Sightings of the rarest type a measuring pass aims for.
///
/// Deliberately well above [`MIN_HAND_TYPE_SAMPLE`], which is the floor below
/// which a levelling is worth warning about. Stopping at the floor would leave
/// every scenario measured to the worst precision anyone would accept — 500
/// sightings is ±4.5% on that rate, and it passes straight into the delivered
/// mix. 2000 is ±2.2%, and the difference costs seconds: the measuring pass
/// deals nothing it has to render, score or keep.
pub const MEASURE_GOAL: usize = 2_000;

/// Fewest sightings of a type worth dividing by.
///
/// A keep is `mix / natural`, so a relative error in a measured rate passes
/// straight into the delivered mix. At 500 sightings that error is about 4.5%,
/// which is a point on a 20% target — a reasonable place for a hard stop.
pub const MIN_HAND_TYPE_SAMPLE: usize = 500;

/// Read `--level-target`: "even", or one weight per hand type.
pub fn parse_level_target(spec: &str, labels: &[String]) -> Result<Vec<f64>, String> {
    let weights: Vec<f64> = if spec.eq_ignore_ascii_case("even") {
        vec![1.0; labels.len()]
    } else {
        let parsed: Result<Vec<f64>, _> =
            spec.split(',').map(|w| w.trim().parse::<f64>()).collect();
        let parsed = parsed.map_err(|_| {
            format!(
                "--level-target `{}` is not `even` or a list of numbers",
                spec
            )
        })?;
        if parsed.len() != labels.len() {
            return Err(format!(
                "--level-target has {} weights for {} hand types",
                parsed.len(),
                labels.len()
            ));
        }
        if parsed.iter().any(|w| *w < 0.0) {
            return Err("--level-target weights cannot be negative".to_string());
        }
        parsed
    };
    let total: f64 = weights.iter().sum();
    if total <= 0.0 {
        return Err("--level-target weights sum to zero".to_string());
    }
    Ok(weights.into_iter().map(|w| w / total).collect())
}

/// One hand type's share of the run, and what to do about it.
pub struct LevelPlan {
    /// The hand type's name, with the `HandType` prefix stripped.
    pub name: String,
    /// Its share of the deals the scenario produces, as measured.
    pub natural: f64,
    /// The share asked for.
    pub target: f64,
    /// The share the keeps will actually deliver, which is the target unless a
    /// budget relaxed it.
    pub mix: f64,
    /// How often to keep this type, scaled so the largest keep is 1.
    pub keep: f64,
    /// How many deals it was measured over.
    pub seen: usize,
}

/// Work out the keeps that would bring `natural` to `target`.
///
/// `keep = mix / natural`, scaled so the largest is 1 — keep the type that is
/// furthest from its target always, and every other in proportion. The cost
/// follows from the single worst ratio rather than from a sum:
///
/// ```text
/// acceptance = 1 / max(target_j / natural_j)
/// ```
///
/// When that is dearer than the budget allows, exactness is relaxed rather than
/// the rarest type sacrificed: every type moves the same fraction `lambda` of
/// the way from nature toward its target. The cost is affine in `lambda`, so
/// the affordable fraction is closed-form and there is nothing to search for.
pub fn level_plan(
    names: &[String],
    natural: &[f64],
    target: &[f64],
    seen: &[usize],
    budget_acceptance: Option<f64>,
) -> (Vec<LevelPlan>, f64, f64) {
    let ratio_max = target
        .iter()
        .zip(natural)
        .map(|(t, n)| if *n > 0.0 { t / n } else { 0.0 })
        .fold(0.0f64, f64::max);

    let lambda = match budget_acceptance {
        Some(budget) if ratio_max > 1.0 => {
            (((1.0 / budget) - 1.0) / (ratio_max - 1.0)).clamp(0.0, 1.0)
        }
        _ => 1.0,
    };
    let acceptance = if ratio_max > 1.0 {
        1.0 / (1.0 + lambda * (ratio_max - 1.0))
    } else {
        1.0
    };

    let mix: Vec<f64> = natural
        .iter()
        .zip(target)
        .map(|(n, t)| (1.0 - lambda) * n + lambda * t)
        .collect();
    let scale = mix
        .iter()
        .zip(natural)
        .map(|(m, n)| if *n > 0.0 { m / n } else { 0.0 })
        .fold(0.0f64, f64::max);

    let plans = (0..names.len())
        .map(|i| LevelPlan {
            name: names[i].clone(),
            natural: natural[i],
            target: target[i],
            mix: mix[i],
            keep: if natural[i] > 0.0 && scale > 0.0 {
                (mix[i] / natural[i]) / scale
            } else {
                0.0
            },
            seen: seen[i],
        })
        .collect();
    (plans, lambda, acceptance)
}

/// Reorder produced deals so a practice set walks through the categories.
///
/// Naive round-robin empties the small buckets first, so the last rounds lose
/// types — exactly the lumpiness the ordering is meant to remove. Instead each
/// bucket's deals are spread evenly across the whole run: with shares of
/// 20/20/20/20/10/10, the four common types appear in every round and the two
/// rare ones in alternate rounds, so every round holds five deals rather than
/// six and then four.
///
/// The spreading is Bresenham's, one accumulator per bucket. Buckets of equal
/// size are given staggered starting credit, or two half-density types would
/// land in the same rounds and leave the others empty.
///
/// Deals carrying no type are dealt out last, in the order they were produced:
/// they belong to no round, and dropping them would lose deals the script
/// asked for.
/// The buckets of one round, in a shuffled order.
///
/// Fisher-Yates over a splitmix64 stream keyed by the run's seed and the round
/// number. Small and self-contained rather than reaching for the deal
/// generator's RNG: this decides a reading order, not a hand, and mixing the
/// two streams would make the deals depend on how many hand types a script
/// happens to declare.
fn round_order(seed: u64, round: usize, count: usize) -> Vec<usize> {
    let mut state = seed
        .wrapping_mul(0x9e37_79b9_7f4a_7c15)
        .wrapping_add(round as u64)
        .wrapping_add(0x8ebc_6af0_9c88_c6e3);
    let mut next = || {
        state = state.wrapping_add(0x9e37_79b9_7f4a_7c15);
        let mut z = state;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    };
    let mut order: Vec<usize> = (0..count).collect();
    for i in (1..count).rev() {
        let j = (next() % (i as u64 + 1)) as usize;
        order.swap(i, j);
    }
    order
}

pub fn interleave(
    order: &[&str],
    mut buckets: Vec<(Option<String>, Vec<usize>)>,
    seed: u64,
) -> Vec<usize> {
    // Declaration order, which decides which bucket is which and where the
    // untyped one goes. It is not the order the round is dealt in — see below.
    buckets.sort_by_key(|(name, _)| match name {
        Some(n) => order.iter().position(|o| o == n).unwrap_or(usize::MAX),
        None => usize::MAX,
    });
    let untyped = match buckets.last() {
        Some((None, _)) => buckets.pop().map(|(_, deals)| deals).unwrap_or_default(),
        _ => Vec::new(),
    };
    if buckets.is_empty() {
        return untyped;
    }

    let rounds = buckets.iter().map(|(_, d)| d.len()).max().unwrap_or(0);
    // Stagger within groups of equal size: buckets of the same density
    // otherwise share a phase and pile into the same rounds.
    let mut credit = vec![0f64; buckets.len()];
    let mut seen: std::collections::HashMap<usize, usize> = std::collections::HashMap::new();
    let sizes: Vec<usize> = buckets.iter().map(|(_, d)| d.len()).collect();
    for (i, size) in sizes.iter().enumerate() {
        let group = sizes.iter().filter(|s| *s == size).count();
        let position = seen.entry(*size).or_insert(0);
        // Half a step of credit to start with, so a bucket holding one deal
        // lands in the middle of the run rather than at the very end.
        credit[i] = (*position as f64 + 0.5) / group as f64;
        *position += 1;
    }

    let mut taken = vec![0usize; buckets.len()];
    let mut out = Vec::new();
    for round in 0..rounds {
        // Shuffled within the round, not dealt in declaration order. A set that
        // walks 12_14, 15_17, 18_19, 20_21, 22_24 and then does it again reads
        // as the natural frequency it was levelled away from — commonest first,
        // every time — and a student meeting the same sequence in every round
        // learns the sequence. Which bucket contributes to a round is settled
        // above and unaffected; only the order they come out in changes.
        //
        // Derived from the run's seed, so a seed still reproduces its set
        // exactly, and from the round number, so two rounds do not share a
        // permutation.
        for i in round_order(seed, round, buckets.len()) {
            let (_, deals) = &buckets[i];
            if deals.is_empty() {
                continue;
            }
            credit[i] += deals.len() as f64 / rounds as f64;
            if credit[i] >= 1.0 - 1e-9 && taken[i] < deals.len() {
                credit[i] -= 1.0;
                out.push(deals[taken[i]]);
                taken[i] += 1;
            }
        }
    }
    // Rounding can leave a deal or two behind; they follow in order.
    for (i, (_, deals)) in buckets.iter().enumerate() {
        out.extend(deals[taken[i]..].iter().copied());
    }
    out.extend(untyped);
    out
}

/// The prefix that marks a variable as naming a category of hand.
///
/// A convention rather than syntax, so a script using it still parses
/// everywhere the original does — which matters, because these scenarios run on
/// BBO. The cost is that a misspelled name is silently not a category, so the
/// count found is always reported.
pub const HAND_TYPE_PREFIX: &str = "HandType";

/// The suffix that marks a variable as a hand type's target share rather than
/// a hand type.
///
/// `HandType_12_Share = 3` says the `12` type is wanted three times as often as
/// one with a share of 1. Written in the script rather than passed as a switch
/// so a scenario carries its own intended mix — the browser then needs no
/// control for it, and the two front ends cannot disagree.
///
/// Still only a variable assignment, so a script using it parses on BBO exactly
/// as the `HandType_` convention does.
///
/// Matched without regard to case, because the failure otherwise is silent and
/// nasty: `HandType_12_share` that was not recognised would simply become a
/// hand type called `12_share`, overlapping the real one.
pub const SHARE_SUFFIX: &str = "_Share";

/// Whether this name declares a share rather than a hand type.
fn is_share(name: &str) -> bool {
    name.len() > SHARE_SUFFIX.len()
        && name[name.len() - SHARE_SUFFIX.len()..].eq_ignore_ascii_case(SHARE_SUFFIX)
}

/// The prefix that marks a variable as naming a category to *level* on, where
/// that is not the same as the category to present.
///
/// Optional, and most scenarios will never need it: where the categories you
/// level are also the ones you talk about, `HandType_` is both.
///
/// It earns its place when the two come apart. Levelling five HCP bands leaves
/// the inside of each band as nature had it — within 12-14 a 12 is far commoner
/// than a 14 — and the fix is to level on each HCP separately. But making those
/// the hand types would put them in the PBN tags, the bar chart and, worst,
/// `--interleave`: thirteen categories walked one at a time means the first
/// thirteen boards hold seven strong hands, and the fine split meant to correct
/// a detail becomes the coarse thing a student notices.
///
/// So the two are separated. `HandType_` stays what the deals are grouped,
/// tagged and ordered by; `LevelType_` is an independent decomposition used for
/// nothing but working out the keeps. They need not nest.
pub const LEVEL_TYPE_PREFIX: &str = "LevelType";

/// The script's level-type variables, in the order it declares them.
pub fn level_types(program: &Program) -> Vec<&str> {
    named_with(program, LEVEL_TYPE_PREFIX)
}

/// A level type's name without its prefix, and without the separator after it.
pub fn level_type_label(name: &str) -> &str {
    name.trim_start_matches(LEVEL_TYPE_PREFIX)
        .trim_start_matches(['_', '-'])
}

/// Variables with a given prefix, in declaration order, skipping shares.
///
/// `LevelType_` is checked before `HandType_` where both could match, but they
/// cannot: neither prefix is a prefix of the other.
fn named_with<'a>(program: &'a Program, prefix: &str) -> Vec<&'a str> {
    let mut found = Vec::new();
    for statement in &program.statements {
        if let Statement::Assignment { name, .. } = statement {
            if name.starts_with(prefix) && !is_share(name) && !found.contains(&name.as_str()) {
                found.push(name.as_str());
            }
        }
    }
    found
}

/// The script's hand-type variables, in the order it declares them.
///
/// Declaration order, not alphabetical: it is the order the author thought in,
/// and it is what an interleaved practice set walks through.
pub fn hand_types(program: &Program) -> Vec<&str> {
    named_with(program, HAND_TYPE_PREFIX)
}

/// The target share each hand type asks for, in declaration order.
///
/// Weights rather than percentages — they are normalised — so `1,1,2` and
/// `10,10,20` say the same thing. A type that declares no share gets 1, which
/// makes an even split the default and means a scenario has to say nothing at
/// all to get the old behaviour.
///
/// The case this exists for: bins that should come out equal while the values
/// inside each bin are also level. Five bins of 3, 3, 2, 2 and 3 HCP values
/// need shares of 2, 2, 3, 3 and 2 — a value in a two-wide bin is wanted half
/// again as often as one in a three-wide bin, and working that out by hand is
/// exactly the sort of arithmetic that ends up wrong in a comment.
/// The decomposition a scenario is levelled on, and what each part asks for.
///
/// `LevelType_` when the scenario declares any, `HandType_` otherwise. They are
/// independent of each other: a level type need not sit inside one hand type,
/// and nothing checks that it does, because the two answer different questions
/// — one is what the keeps are computed from, the other is what the deals are
/// grouped, tagged and ordered by.
#[derive(Debug)]
pub struct LevelingTypes {
    /// Variable names as written, e.g. `LevelType_12`, in declaration order.
    pub names: Vec<String>,
    /// The same without their prefix, e.g. `12`.
    pub labels: Vec<String>,
    /// Target weight per label, defaulting to 1.
    pub shares: Vec<f64>,
    /// Which prefix these came from, for the generated block to write.
    pub prefix: &'static str,
}

/// Work out which decomposition to level on, and the weights it asks for.
pub fn leveling_types(program: &Program) -> Result<LevelingTypes, String> {
    let level = level_types(program);
    let prefix = if level.is_empty() {
        HAND_TYPE_PREFIX
    } else {
        LEVEL_TYPE_PREFIX
    };

    // A share says which kind it weights by its own prefix, so a script that
    // weights both has asked for two different target mixes. Picking one and
    // ignoring the other would deliver a mix nobody asked for and say nothing.
    let mut weights_hand = false;
    let mut weights_level = false;
    for statement in &program.statements {
        if let Statement::Assignment { name, .. } = statement {
            if !is_share(name) {
                continue;
            }
            if name.starts_with(LEVEL_TYPE_PREFIX) {
                weights_level = true;
            } else if name.starts_with(HAND_TYPE_PREFIX) {
                weights_hand = true;
            }
        }
    }
    if weights_hand && weights_level {
        return Err(format!(
            "the scenario sets both `{}_..._Share` and `{}_..._Share`.\n       Only one \
             decomposition is levelled — `{}_` when the scenario declares any, `{}_` \
             otherwise — so weighting both asks for two different mixes.\n       Keep the \
             shares on the one being levelled and drop the others.",
            HAND_TYPE_PREFIX, LEVEL_TYPE_PREFIX, LEVEL_TYPE_PREFIX, HAND_TYPE_PREFIX
        ));
    }
    if weights_hand && !level.is_empty() {
        return Err(format!(
            "the scenario declares `{}_` variables, so those are what it levels — but the \
             shares are on `{}_`.\n       Move them to the `{}_` they weight.",
            LEVEL_TYPE_PREFIX, HAND_TYPE_PREFIX, LEVEL_TYPE_PREFIX
        ));
    }

    let names: Vec<String> = named_with(program, prefix)
        .into_iter()
        .map(str::to_string)
        .collect();
    let labels: Vec<String> = names
        .iter()
        .map(|n| strip_prefix(n, prefix).to_string())
        .collect();
    let shares = shares_for(program, prefix, &labels)?;
    Ok(LevelingTypes {
        names,
        labels,
        shares,
        prefix,
    })
}

/// A name without its prefix, and without the separator after it.
fn strip_prefix<'a>(name: &'a str, prefix: &str) -> &'a str {
    name.trim_start_matches(prefix)
        .trim_start_matches(['_', '-'])
}

pub fn hand_type_shares(program: &Program) -> Result<Vec<f64>, String> {
    let labels: Vec<String> = hand_types(program)
        .into_iter()
        .map(|n| hand_type_label(n).to_string())
        .collect();
    shares_for(program, HAND_TYPE_PREFIX, &labels)
}

/// The share each label asks for, for one decomposition.
///
/// The prefix decides which: `LevelType_12_Share` weights a level type,
/// `HandType_12_14_Share` a hand type. A scenario that sets both is refused by
/// [`leveling_types`] before this is reached.
fn shares_for(program: &Program, prefix: &str, labels: &[String]) -> Result<Vec<f64>, String> {
    let mut shares = vec![1.0; labels.len()];

    for statement in &program.statements {
        let Statement::Assignment { name, expr } = statement else {
            continue;
        };
        if !name.starts_with(prefix) || !is_share(name) {
            continue;
        }
        let label = strip_prefix(name, prefix);
        let label = &label[..label.len() - SHARE_SUFFIX.len()];

        let index = labels.iter().position(|l| l == label).ok_or_else(|| {
            format!(
                "`{}` sets the share of a `{}` the scenario never \
                     declares.\n       Add `{}_{} = ...`, or correct the name.",
                name, label, prefix, label
            )
        })?;

        // A share has to be known before a card is dealt, so it is a number and
        // not an expression. Anything else is a mistake worth naming rather
        // than a feature: a share that depended on the deal would mean a
        // different target mix on every hand.
        let Expr::Literal(value) = expr else {
            return Err(format!(
                "`{}` has to be a plain number — it is a target share, settled before any \
                 deal is looked at.",
                name
            ));
        };
        if *value < 0 {
            return Err(format!("`{}` cannot be negative.", name));
        }
        shares[index] = *value as f64;
    }

    // Only when there is something to weight: a scenario with no hand types at
    // all is the ordinary case, not a mix of nothing.
    if !shares.is_empty() && shares.iter().sum::<f64>() <= 0.0 {
        return Err("every share is 0, which asks for no deals at all.".to_string());
    }
    Ok(shares)
}

/// Whether an expression is about a hand type.
///
/// A scenario levelling five bands usually carries five `average` statements
/// reporting them, which say the same thing as the hand-type table and would
/// only crowd the averages beside it. The label cannot answer this — it is
/// prose — so the expression is asked instead.
pub fn mentions_hand_type(expr: &Expr) -> bool {
    match expr {
        Expr::Variable(name) => name.starts_with(HAND_TYPE_PREFIX),
        Expr::BinaryOp { left, right, .. } => mentions_hand_type(left) || mentions_hand_type(right),
        Expr::UnaryOp { expr, .. } => mentions_hand_type(expr),
        Expr::Ternary {
            condition,
            true_expr,
            false_expr,
        } => {
            mentions_hand_type(condition)
                || mentions_hand_type(true_expr)
                || mentions_hand_type(false_expr)
        }
        Expr::FunctionCall { args, .. } => args.iter().any(mentions_hand_type),
        _ => false,
    }
}

/// What goes in the `[HandType "..."]` tag: the name without its prefix, and
/// without the separator someone will have written after it.
pub fn hand_type_label(name: &str) -> &str {
    name.trim_start_matches(HAND_TYPE_PREFIX)
        .trim_start_matches(['_', '-'])
}

/// What one measuring pass over a scenario found.
///
/// The front end deals the cards — the command line with its thread pool, the
/// browser with its single loop — and hands back only the counts, which is all
/// the levelling needs.
pub struct Measurement {
    /// Deals that matched the scenario's condition.
    pub produced: usize,
    /// Deals looked at, including those the condition rejected.
    pub generated: usize,
    /// Hand type names, with the `HandType` prefix stripped, in declaration
    /// order.
    pub names: Vec<String>,
    /// How many produced deals matched each, parallel to `names`.
    pub counts: Vec<usize>,
    /// Which prefix `names` came from — `HandType` normally, `LevelType` when
    /// the scenario levels on a decomposition of its own. The generated block
    /// has to name the same variables the script does.
    pub prefix: &'static str,
    /// The presentation groups — the hand types — when those are not what is
    /// being levelled. Empty when they are, since then `names` is already them.
    pub groups: Vec<String>,
    /// How many produced deals fell in each `groups` × `names` pair.
    ///
    /// Needed because the two decompositions are independent: what a hand type
    /// will deliver once the keeps are applied cannot be worked out from its
    /// own rate, only from how its deals were spread across the levelling
    /// categories. `joint[group][name]`.
    pub joint: Vec<Vec<usize>>,
}

/// What a presentation group will deliver once the keeps are applied.
///
/// `joint[g][l]` deals of group `g` were also level type `l`, and each survives
/// at `keep[l]`, so the group's share of what comes out is its weighted row
/// against the whole weighted table.
pub fn group_mix(joint: &[Vec<usize>], keeps: &[f64]) -> Vec<f64> {
    let weighted: Vec<f64> = joint
        .iter()
        .map(|row| {
            row.iter()
                .zip(keeps)
                .map(|(n, k)| *n as f64 * k)
                .sum::<f64>()
        })
        .collect();
    let total: f64 = weighted.iter().sum();
    if total <= 0.0 {
        return vec![0.0; joint.len()];
    }
    weighted.into_iter().map(|w| w / total).collect()
}

/// A levelled scenario, and what it will cost.
pub struct Leveled {
    /// The scenario with its levelling block filled in, ready to run.
    pub script: String,
    /// One per hand type, holding the measured rate, the target and the keep.
    pub plans: Vec<LevelPlan>,
    /// How exactly the target was met: 1 unless a budget relaxed it.
    pub lambda: f64,
    /// The share of qualifying deals the keeps let through.
    pub acceptance: f64,
    /// The share of dealt hands that passed the scenario's own condition.
    pub base_rate: f64,
    /// Anything the caller should say out loud but that does not make the
    /// levelling wrong — a measurement thinner than asked for, above all.
    pub warnings: Vec<String>,
}

/// Work out a scenario's levelling from a measuring pass, and write it in.
///
/// Everything that decides whether a levelling is sound lives here rather than
/// in the front ends: they differ in how they deal cards and in nothing else,
/// and a browser that refused for different reasons than the command line would
/// be its own kind of wrong. `source` should already have been through
/// [`insert_leveling_block`].
pub fn level_from(
    source: &str,
    measured: &Measurement,
    target: &[f64],
    budget: Option<f64>,
    seed: u32,
    min_sample: usize,
) -> Result<Leveled, String> {
    if measured.names.is_empty() {
        return Err(format!(
            "there are no hand types to level. Name them with variables beginning `{}`.",
            HAND_TYPE_PREFIX
        ));
    }
    if measured.produced == 0 {
        return Err("nothing was produced, so there is nothing to measure.".to_string());
    }

    let classified: usize = measured.counts.iter().sum();
    if classified != measured.produced {
        // Usually the condition is simply wider than the types, which is what
        // every scenario looks like when the block it is replacing was
        // filtering as well as levelling: the deals it dropped were never in a
        // category. Naming the remedy saves working that out from scratch.
        return Err(format!(
            "{} of {} deals matched no hand type. They have to partition what the scenario \
             produces,\n       or the keeps will not add up — a rate is only a rate if it is \
             a share of something.\n       Either widen the types, or narrow the condition to \
             the deals they cover:\n\n           and ({})\n",
            measured.produced - classified,
            measured.produced,
            measured
                .names
                .iter()
                .map(|n| format!("{}_{}", HAND_TYPE_PREFIX, n))
                .collect::<Vec<_>>()
                .join(" or ")
        ));
    }

    // A type that never came up at all is refused, not warned about. The keep
    // is `mix / natural`, and there is no keep that turns nothing into a fifth
    // of the deals: this is impossible rather than imprecise, and going on
    // writes a file whose header claims a mix it cannot deliver. Usually the
    // type's definition is wrong — a name that never matches, or a condition
    // narrower than the type it is meant to contain.
    let never: Vec<&str> = measured
        .names
        .iter()
        .zip(&measured.counts)
        .filter(|(_, n)| **n == 0)
        .map(|(l, _)| l.as_str())
        .collect();
    if !never.is_empty() {
        return Err(format!(
            "never seen in {} deals: {}.\n       A keep cannot make a hand that does not \
             occur, so there is no levelling that delivers the asked-for mix.\n       Check \
             those definitions: a type that matches nothing usually means a misspelled name \
             or a condition\n       narrower than the type meant to sit inside it.",
            measured.produced,
            never
                .iter()
                .map(|n| format!("`{}`", n))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }

    // Thin measurements warn rather than refuse. The measuring pass now grows
    // itself toward the goal and stops on a clock, so falling short means the
    // scenario is genuinely expensive to measure — and refusing then would give
    // no file and no way forward, where a warning gives both the file and the
    // number to judge it by. The precision is stamped into the generated
    // scenario as well, so it travels with the file.
    let mut warnings = Vec::new();
    let thin: Vec<String> = measured
        .names
        .iter()
        .zip(&measured.counts)
        .filter(|(_, n)| **n < min_sample)
        .map(|(l, n)| format!("`{}` seen {} times", l, n))
        .collect();
    if !thin.is_empty() {
        warnings.push(format!(
            "measured on fewer than {} deals of {}, over {} produced.\n         A keep is \
             `mix / natural`, so an error in a rate this thin is baked into the mix for good \
             — it does not average out.\n         Raise --level-measure or --level-timeout, \
             or widen the rare types.",
            min_sample,
            thin.join("; "),
            measured.produced
        ));
    }

    let natural: Vec<f64> = measured
        .counts
        .iter()
        .map(|n| *n as f64 / measured.produced as f64)
        .collect();
    if target.len() != measured.names.len() {
        return Err(format!(
            "{} target shares for {} hand types.",
            target.len(),
            measured.names.len()
        ));
    }
    // Weights, not percentages, whether they came from the script's `_Share`
    // declarations or from `--level-target` — so normalising here is what lets
    // both say the same thing.
    let total: f64 = target.iter().sum();
    if total <= 0.0 {
        return Err("the target shares sum to zero, which asks for no deals at all.".to_string());
    }
    let target: Vec<f64> = target.iter().map(|w| w / total).collect();
    let base_rate = measured.produced as f64 / measured.generated.max(1) as f64;
    let budget_acceptance = budget.map(|b| ((1.0 / b) / base_rate).min(1.0));
    let (plans, lambda, acceptance) = level_plan(
        &measured.names,
        &natural,
        &target,
        &measured.counts,
        budget_acceptance,
    );

    // What each presentation group will deliver, once the keeps are applied to
    // the categories its deals actually fell in. Empty when the hand types are
    // themselves what is being levelled, in which case the plans already say.
    let keeps: Vec<f64> = plans.iter().map(|p| p.keep).collect();
    let groups: Vec<(String, f64)> = if measured.groups.is_empty() {
        Vec::new()
    } else {
        measured
            .groups
            .iter()
            .cloned()
            .zip(group_mix(&measured.joint, &keeps))
            .collect()
    };

    let script = render_leveled(
        source,
        &plans,
        lambda,
        acceptance,
        base_rate,
        measured.produced,
        seed,
        measured.prefix,
        &groups,
    )?;
    Ok(Leveled {
        script,
        plans,
        lambda,
        acceptance,
        base_rate,
        warnings,
    })
}

/// Per hand type, what nature offered and what the levelled run delivered.
pub struct HandTypeShare {
    pub name: String,
    /// Its share of the deals the scenario produced before levelling.
    pub natural: f64,
    /// The share the keeps deliver in the long run — the target, unless a
    /// budget relaxed it. This is what the generated scenario's own text says,
    /// so it is the number to show beside it.
    pub planned: f64,
    /// Its share of the deals this run actually produced. Over a short set that
    /// is lumpy however even the keeps are: twenty-four boards across five
    /// bands carry a standard deviation of eight points.
    pub delivered: f64,
    /// How many deals of this type the run produced.
    pub produced: usize,
    /// How many deals the run produced in total, so a caller can say "3 of 24"
    /// without carrying the denominator separately.
    pub out_of: usize,
}

/// What levelling a scenario and running it turned up.
pub struct LevelReport {
    /// The scenario with its levelling filled in — what actually ran, and what
    /// a page can show beside the one that was written.
    pub script: String,
    /// The measured rates, targets and keeps, one per hand type.
    pub plans: Vec<LevelPlan>,
    /// Nature against delivery, one per hand type, in declaration order.
    pub shares: Vec<HandTypeShare>,
    /// How exactly the target was met: 1 unless a budget relaxed it.
    pub lambda: f64,
    /// The share of qualifying deals the keeps let through.
    pub acceptance: f64,
    /// Deals dealt per deal kept.
    pub cost: f64,
    /// How many deals the keeps were measured over.
    pub measured: usize,
    /// Anything worth saying out loud that does not make the levelling wrong.
    pub warnings: Vec<String>,
}

/// What the caller chose about a levelling.
pub struct LevelOptions<'a> {
    /// One weight per hand type, in declaration order. Normalised here, so
    /// these are shares in the `HandType_X_Share` sense rather than fractions.
    pub target: &'a [f64],
    /// A cap on the cost, in deals dealt per deal kept.
    pub budget: Option<f64>,
    pub seed: u32,
    /// Fewest sightings of a type worth dividing by.
    pub min_sample: usize,
    /// How many deals the first, exploratory pass produces.
    ///
    /// Only there to find out how rare the rarest type is. Small, because for
    /// most scenarios it is also enough on its own.
    pub probe_produce: usize,
    /// Most deals the second pass may produce, whatever the probe suggests.
    pub measure_cap: usize,
}

/// Level a scenario and run it, in one call.
///
/// Two passes over the deals, and the engine owns both: measure the scenario as
/// written, work out the keeps, then run the levelled copy. A front end supplies
/// only the dealing, since that is the one part they genuinely differ in — the
/// command line deals across a thread pool with CSV and a timeout, the browser
/// in a single loop it must not block.
///
/// Two closures rather than one with a flag, because the difference is in what
/// comes back. The measuring pass wants counts and nothing else: its deals exist
/// to be characterised and thrown away, and a signature that let it hand them
/// back would invite a front end to render a few thousand boards nobody will
/// look at.
///
/// The shares come back worked out, so no caller has to divide counts by totals
/// and get the denominator subtly wrong.
pub fn level_and_run<T>(
    source: &str,
    opts: &LevelOptions,
    mut measure: impl FnMut(&str, usize) -> Result<Measurement, String>,
    mut produce: impl FnMut(&str) -> Result<(T, Measurement), String>,
) -> Result<(T, LevelReport), String> {
    let prepared = insert_leveling_block(source)?;
    check_leveling_source(&prepared)?;

    // Two passes, not one, and the first is only there to find out how rare
    // the rarest type is. A single fixed size cannot serve both a scenario
    // whose scarcest band is 5% of qualifying deals and one where it is 0.2% —
    // they need ten thousand produced and a million, and guessing high wastes
    // most of a minute on the first while guessing low quietly ruins the
    // second.
    //
    // The measuring closure may return fewer deals than asked for: a front end
    // with a clock to answer to clamps the request to what fits, and what comes
    // back is what was actually dealt.
    let probe = measure(&prepared, opts.probe_produce)?;
    let needed = needed_produce(&probe.counts, probe.produced, MEASURE_GOAL);
    let measured = if needed > probe.produced {
        measure(&prepared, needed.min(opts.measure_cap))?
    } else {
        probe
    };
    let leveled = level_from(
        &prepared,
        &measured,
        opts.target,
        opts.budget,
        opts.seed,
        opts.min_sample,
    )?;

    let (outcome, delivered) = produce(&leveled.script)?;

    let natural_of = |name: &str| {
        measured
            .names
            .iter()
            .position(|n| n == name)
            .map(|i| measured.counts[i] as f64 / measured.produced.max(1) as f64)
            .unwrap_or(0.0)
    };
    let planned_of = |name: &str| {
        leveled
            .plans
            .iter()
            .find(|p| p.name == name)
            .map(|p| p.mix)
            .unwrap_or(0.0)
    };
    let shares = delivered
        .names
        .iter()
        .zip(&delivered.counts)
        .map(|(name, count)| HandTypeShare {
            natural: natural_of(name),
            planned: planned_of(name),
            delivered: *count as f64 / delivered.produced.max(1) as f64,
            produced: *count,
            out_of: delivered.produced,
            name: name.clone(),
        })
        .collect();

    let base_rate = measured.produced as f64 / measured.generated.max(1) as f64;
    Ok((
        outcome,
        LevelReport {
            script: leveled.script,
            plans: leveled.plans,
            shares,
            lambda: leveled.lambda,
            acceptance: leveled.acceptance,
            cost: 1.0 / (base_rate * leveled.acceptance),
            measured: measured.produced,
            warnings: leveled.warnings,
        },
    ))
}

#[cfg(test)]
mod interleave_tests {
    use super::interleave;

    fn buckets(sizes: &[(&str, usize)]) -> Vec<(Option<String>, Vec<usize>)> {
        let mut next = 0;
        let mut out = Vec::new();
        for (name, n) in sizes {
            out.push((Some((*name).to_string()), (next..next + n).collect()));
            next += n;
        }
        out
    }

    /// Which bucket each position in the result came from.
    fn shape(order: &[&str], sizes: &[(&str, usize)]) -> Vec<usize> {
        let b = buckets(sizes);
        let total: usize = sizes.iter().map(|(_, n)| n).sum();
        let mut owner = vec![0usize; total];
        for (i, (_, deals)) in b.iter().enumerate() {
            for d in deals {
                owner[*d] = i;
            }
        }
        interleave(order, b, 1)
            .into_iter()
            .map(|d| owner[d])
            .collect()
    }

    #[test]
    fn equal_buckets_come_out_one_of_each_per_round() {
        let got = shape(&["a", "b", "c"], &[("a", 3), ("b", 3), ("c", 3)]);
        assert_eq!(got.len(), 9);
        for round in got.chunks(3) {
            let mut seen = round.to_vec();
            seen.sort_unstable();
            assert_eq!(seen, vec![0, 1, 2], "every round should hold one of each");
        }
    }

    /// The case naive round-robin gets wrong: two half-size buckets have to
    /// land in alternate rounds, not both in the first half, or the last
    /// rounds lose types — the very lumpiness the ordering removes.
    #[test]
    fn half_size_buckets_alternate_instead_of_running_out() {
        let got = shape(
            &["a", "b", "c", "d"],
            &[("a", 4), ("b", 4), ("c", 2), ("d", 2)],
        );
        assert_eq!(got.len(), 12);
        for (i, round) in got.chunks(3).enumerate() {
            assert!(round.contains(&0), "round {i} lost `a`: {round:?}");
            assert!(round.contains(&1), "round {i} lost `b`: {round:?}");
            assert!(
                round.contains(&2) ^ round.contains(&3),
                "round {i} should hold exactly one rare type: {round:?}"
            );
        }
    }

    #[test]
    fn every_deal_comes_out_exactly_once() {
        for sizes in [
            vec![("a", 7), ("b", 3), ("c", 1)],
            vec![("a", 1), ("b", 1)],
            vec![("a", 10)],
            vec![("a", 5), ("b", 5), ("c", 5), ("d", 2), ("e", 1)],
        ] {
            let order: Vec<&str> = sizes.iter().map(|(n, _)| *n).collect();
            let total: usize = sizes.iter().map(|(_, n)| n).sum();
            let mut got = interleave(&order, buckets(&sizes), 1);
            assert_eq!(got.len(), total, "for {sizes:?}");
            got.sort_unstable();
            assert_eq!(got, (0..total).collect::<Vec<_>>(), "for {sizes:?}");
        }
    }

    /// Deals the script did not classify still have to appear, or a run would
    /// silently produce fewer boards than it reports.
    #[test]
    fn untyped_deals_follow_at_the_end() {
        let b = vec![
            (Some("a".to_string()), vec![0, 1]),
            (None, vec![2, 3]),
            (Some("b".to_string()), vec![4, 5]),
        ];
        let got = interleave(&["a", "b"], b, 1);
        assert_eq!(got.len(), 6);
        assert_eq!(&got[4..], &[2, 3], "untyped deals come last, in order");
    }

    /// One of each per round is the point; which order they come out in inside
    /// that round is not, and holding it fixed does harm. A set that walks the
    /// types in declaration order every round reads as the natural frequency it
    /// was levelled away from — for the NT ladder that order is also commonest
    /// first — and a student meeting the same sequence every round learns the
    /// sequence rather than the hands.
    #[test]
    fn the_order_within_a_round_varies() {
        let five = || {
            (0..5)
                .map(|i| (Some(format!("t{i}")), (0..4).map(|d| i * 10 + d).collect()))
                .collect::<Vec<_>>()
        };
        let names: Vec<String> = (0..5).map(|i| format!("t{i}")).collect();
        let order: Vec<&str> = names.iter().map(String::as_str).collect();

        // Rounds of five, each holding one of every type.
        let got = interleave(&order, five(), 7);
        assert_eq!(got.len(), 20);
        for round in got.chunks(5) {
            let mut types: Vec<usize> = round.iter().map(|d| d / 10).collect();
            types.sort_unstable();
            assert_eq!(types, vec![0, 1, 2, 3, 4], "every round holds one of each");
        }

        // Two rounds of the same run do not share a permutation.
        let first: Vec<usize> = got[..5].iter().map(|d| d / 10).collect();
        let differs = got
            .chunks(5)
            .skip(1)
            .any(|r| r.iter().map(|d| d / 10).collect::<Vec<_>>() != first);
        assert!(
            differs,
            "every round dealt the types in the same order: {got:?}"
        );

        // And two seeds do not share one either.
        let other = interleave(&order, five(), 8);
        assert_ne!(got, other, "the seed should change the order");
    }

    #[test]
    fn a_seed_still_reproduces_its_set() {
        // The shuffle is derived from the seed, so a run is as repeatable as it
        // was before — which is the whole basis of quoting one.
        let b = || {
            vec![
                (Some("a".to_string()), vec![1, 2, 3]),
                (Some("b".to_string()), vec![4, 5, 6]),
                (Some("c".to_string()), vec![7, 8, 9]),
            ]
        };
        assert_eq!(
            interleave(&["a", "b", "c"], b(), 42),
            interleave(&["a", "b", "c"], b(), 42)
        );
    }
}
