import { describe, it, expect } from 'vitest'
import { tags } from '@lezer/highlight'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import {
  dlrStreamParser,
  dlrCompletion,
  tokenizeLine,
  DLR_TOKENS,
  DLR_TOKEN_CLASSES,
  METADATA_KEYS,
} from './dlrLanguage.js'

// Shaped like the engine's language_info() output.
const info = {
  functions: ['hcp', 'shape', 'spade', 'spades', 'top2', 'pt0', 'cccc'],
  statement_keywords: ['condition', 'produce', 'csvrpt'],
  actions: ['printall', 'printoneline'],
  positions: ['north', 'south', 'n', 's'],
  vulnerabilities: ['none', 'all'],
  logical_words: ['and', 'or', 'not'],
  other_keywords: ['any', 'deal'],
  operators: ['==', '>=', '>', '='],
  // As `language_info()` sends it, from the constants in dealer-level.
  leveling: {
    hand_type_prefix: 'HandType',
    level_type_prefix: 'LevelType',
    share_suffix: '_Share',
    verdicts: ['levelTheDeal', 'keepTheDeal'],
    no_leveling: 'noLeveling',
    block_begin: '### BEGIN GENERATED LEVELING ###',
    block_end: '### END GENERATED LEVELING ###',
    stamp: '# Generated by dealer --write-leveled',
  },
}

/** Run the stream tokenizer over a line and return [token, text] pairs. */
function tokenize(line, parser = dlrStreamParser(info)) {
  const state = parser.startState()
  const out = []
  let pos = 0
  const stream = {
    pos: 0,
    string: line,
    sol() { return this.pos === 0 },
    peek() { return this.string[this.pos] },
    next() { return this.string[this.pos++] },
    eatSpace() {
      const start = this.pos
      while (/\s/.test(this.string[this.pos])) this.pos++
      return this.pos > start
    },
    skipToEnd() { this.pos = this.string.length },
    match(pattern, consume = true) {
      if (typeof pattern === 'string') {
        if (this.string.startsWith(pattern, this.pos)) {
          if (consume) this.pos += pattern.length
          return true
        }
        return false
      }
      const m = this.string.slice(this.pos).match(pattern)
      if (m && m.index === 0) {
        if (consume) this.pos += m[0].length
        return m
      }
      return null
    },
  }
  let guard = 0
  while (stream.pos < line.length && guard++ < 500) {
    pos = stream.pos
    const tok = parser.token(stream, state)
    if (stream.pos === pos) stream.pos++
    if (tok) out.push([tok, line.slice(pos, stream.pos).trim()])
  }
  return out
}

describe('dlr tokenizer', () => {
  it('marks known functions as functions', () => {
    const t = tokenize('hcp(north) >= 15')
    expect(t.find(([, text]) => text === 'hcp')[0]).toBe('function')
  })

  it('marks statement keywords as keywords', () => {
    expect(tokenize('condition x')[0][0]).toBe('keyword')
    // csvrpt was missing from the old TextMate grammar entirely.
    expect(tokenize('csvrpt(deal)')[0][0]).toBe('keyword')
  })

  it('covers point-count functions the old grammar missed', () => {
    for (const fn of ['top2', 'pt0']) {
      const t = tokenize(`${fn}(north)`)
      expect(t[0], `${fn} should tokenize`).toEqual(['function', fn])
    }
  })

  it('does not mistake a longer word for a shorter function', () => {
    // `spades` must not tokenize as `spade` + `s`.
    const t = tokenize('spades(north)')
    expect(t[0]).toEqual(['function', 'spades'])
  })

  it('leaves unknown identifiers as variables', () => {
    const t = tokenize('myOpener = 1')
    expect(t[0]).toEqual(['variableName', 'myOpener'])
  })

  it('does not colour single-letter positions', () => {
    // `n` is a valid position but also a common variable name, and the
    // evaluator lets a variable shadow it.
    expect(tokenize('n = 4')[0][0]).toBe('variableName')
    expect(tokenize('north')[0][0]).toBe('atom')
  })

  it('is case-insensitive, matching the grammar', () => {
    expect(tokenize('HCP(NORTH)')[0][0]).toBe('function')
  })

  it('recognises comments', () => {
    expect(tokenize('# just a comment')[0][0]).toBe('comment')
    expect(tokenize('// slash comment')[0][0]).toBe('comment')
  })

  it('recognises shape patterns before numbers', () => {
    expect(tokenize('4333')[0]).toEqual(['number', '4333'])
    expect(tokenize('5xxx')[0]).toEqual(['number', '5xxx'])
  })

  it('recognises card literals and predeal holdings', () => {
    expect(tokenize('AS')[0][0]).toBe('atom')
    expect(tokenize('SAKQ')[0][0]).toBe('atom')
  })

  it('tracks block comments across a line', () => {
    const parser = dlrStreamParser(info)
    const state = parser.startState()
    expect(state.inBlockComment).toBe(false)
  })
})

describe('PBS metadata headers', () => {
  it('separates the key from the value', () => {
    const t = tokenize('# scenario-title: Jacoby 2NT')
    expect(t[0]).toEqual(['metaKey', '# scenario-title:'])
    expect(t[1]).toEqual(['metaValue', 'Jacoby 2NT'])
  })

  it('recognises every key the scenario corpus uses', () => {
    for (const key of METADATA_KEYS) {
      expect(tokenize(`# ${key}: something`)[0][0], key).toBe('metaKey')
    }
  })

  it('leaves a mistyped key an ordinary comment', () => {
    // The point of the list: `scenario-titel` reads as prose, not as a header
    // that works. It was indistinguishable from the real thing before.
    const t = tokenize('# scenario-titel: Jacoby 2NT')
    expect(t.length).toBe(1)
    expect(t[0][0]).toBe('comment')
  })

  it('does not read a header value as code', () => {
    // `Jacoby` is a variable everywhere else in the language.
    const t = tokenize('# button-text: hcp and shape')
    expect(t.map(([token]) => token)).toEqual(['metaKey', 'metaValue'])
  })

  it('does not let an empty value swallow the next line', () => {
    // A header with nothing after the colon leaves no value to consume, so the
    // flag saying "the rest of this line is a value" has to clear itself.
    const parser = dlrStreamParser(info)
    const state = parser.startState()
    tokenizeLine(parser, '# alias:', state)
    expect(tokenizeLine(parser, 'HandType_12 = 1', state)[0]).toEqual([
      'levelingName',
      'HandType_12',
    ])
  })
})

describe('the levelling conventions', () => {
  it('marks the two decompositions', () => {
    expect(tokenize('HandType_12_14 = 1')[0]).toEqual(['levelingName', 'HandType_12_14'])
    expect(tokenize('LevelType_12 = 1')[0]).toEqual(['levelingName', 'LevelType_12'])
  })

  it('marks a share apart from the type it weights', () => {
    expect(tokenize('HandType_12_Share = 3')[0]).toEqual(['levelingShare', 'HandType_12_Share'])
    // Matched without regard to case, as `dealer_level::is_share` matches it.
    expect(tokenize('HandType_12_share = 3')[0][0]).toBe('levelingShare')
  })

  it('leaves a share with no type prefix an ordinary variable', () => {
    // Nothing reads it: a share is only found under a type's prefix.
    expect(tokenize('profit_Share = 3')[0][0]).toBe('variableName')
  })

  it('respects the case the engine matches prefixes in', () => {
    // `starts_with` is case-sensitive, so `handtype_12` is silently not a hand
    // type. Colouring it as one would be the highlighter telling a lie the
    // engine will not back up.
    expect(tokenize('handtype_12 = 1')[0][0]).toBe('variableName')
  })

  it('marks the verdict and its placeholder', () => {
    expect(tokenize('levelTheDeal = 1')[0][0]).toBe('levelingName')
    expect(tokenize('keepTheDeal = 1')[0][0]).toBe('levelingName')
    expect(tokenize('noLeveling = 1')[0][0]).toBe('levelingName')
  })

  it('marks the generated block markers and stamp, which are comments', () => {
    expect(tokenize('### BEGIN GENERATED LEVELING ###')[0][0]).toBe('levelingMarker')
    expect(tokenize('### END GENERATED LEVELING ###')[0][0]).toBe('levelingMarker')
    const stamp = tokenize('# Generated by dealer --write-leveled. Do not edit; edit the stock')
    expect(stamp.length).toBe(1)
    expect(stamp[0][0]).toBe('levelingMarker')
  })

  it("leaves the block's own arithmetic comments as comments", () => {
    expect(tokenize('# type     natural    target')[0][0]).toBe('comment')
  })

  it('colours nothing when the engine sends no levelling names', () => {
    // An engine too old to carry them: plain variables, not a guess.
    const older = { ...info, leveling: undefined }
    const parser = dlrStreamParser(older)
    expect(tokenize('HandType_12 = 1', parser)[0][0]).toBe('variableName')
    expect(tokenize('### BEGIN GENERATED LEVELING ###', parser)[0][0]).toBe('comment')
  })
})

describe('dlr completion', () => {
  const complete = dlrCompletion(info)
  const context = (text, explicit = false) => ({
    explicit,
    matchBefore: (re) => {
      const m = text.match(re)
      return m ? { from: text.length - m[0].length, to: text.length, text: m[0] } : null
    },
  })

  it('offers every function from the vocabulary', () => {
    const r = complete(context('hc'))
    for (const f of info.functions) {
      expect(r.options.some((o) => o.label === f), `${f} missing`).toBe(true)
    }
  })

  it('completes functions with their parentheses', () => {
    const r = complete(context('hc'))
    expect(r.options.find((o) => o.label === 'hcp').apply).toBe('hcp()')
  })

  it('labels the kind of each suggestion', () => {
    const r = complete(context('co'))
    expect(r.options.find((o) => o.label === 'condition').detail).toBe('statement')
    expect(r.options.find((o) => o.label === 'north').detail).toBe('position')
  })

  it('returns nothing on an empty implicit request', () => {
    expect(complete(context(''))).toBeNull()
  })
})

describe('the token table', () => {
  // The tokeniser returning a name is only half of it: CodeMirror has to be
  // able to resolve that name to a highlight tag, and it silently styles
  // nothing when it cannot. `function` is a modifier in @lezer/highlight
  // rather than a tag, so it needs saying explicitly — which is why every
  // function in every script rendered as plain text while the test above,
  // asserting `hcp` tokenises as `function`, passed.
  it('maps every token name the parser emits', () => {
    const emitted = new Set()
    const parser = dlrStreamParser(info)
    const lines = [
      'x = hcp(north) >= 15 and shape(south, any 4333)',
      '# a comment',
      'action average "label" cccc(west), printall',
      'predeal north SAKQ, HT62',
      'condition top2(north, spades) == 2 ? 1 : 0',
      '# scenario-title: NT Ladder',
      '### BEGIN GENERATED LEVELING ###',
      'HandType_12_14 = hcp(south) >= 12',
      'HandType_12_14_Share = 2',
    ]
    for (const line of lines) {
      for (const [token] of tokenize(line, parser)) if (token) emitted.add(token)
    }
    for (const name of emitted) {
      const resolvable = tags[name] !== undefined || DLR_TOKENS[name] !== undefined
      expect(resolvable, `\`${name}\` resolves to no highlight tag, so it is styled as nothing`)
        .toBe(true)
    }
    // And the one that caught this.
    expect(emitted.has('function')).toBe(true)
  })

  // A tag is only half of it too. The levelling and header tokens map to tags
  // the base theme already claims, so they are styled through named classes
  // instead — and a class with no rule behind it is the same silent nothing.
  // The VS Code extension highlights the same files from a TextMate grammar,
  // which is generated from this list because nothing in the engine owns it.
  // Two editors disagreeing about which headers work is the drift this catches.
  it('names the same metadata keys as the TextMate grammar', () => {
    const grammar = readFileSync(
      fileURLToPath(new URL('../../../dealer-parser/syntaxes/dlr.tmLanguage.json', import.meta.url)),
      'utf8',
    )
    const rule = JSON.parse(grammar).repository.comments.patterns.find(
      (p) => p.name === 'comment.line.hash.metadata.dlr',
    )
    for (const key of METADATA_KEYS) {
      expect(rule.match.includes(key), `${key} is not in the TextMate grammar`).toBe(true)
    }
  })

  //
  // Read from `dlrTokenColors`, which the language ships, rather than from a
  // component: while these rules lived in `ScriptEditor.vue` the read-only
  // viewer behind the Leveled tab emitted every class and coloured none of
  // them, and this test passed throughout because it was looking at the one
  // component that happened to be right.
  it('has a rule behind every class it asks for', () => {
    const language = readFileSync(
      fileURLToPath(new URL('./dlrLanguage.js', import.meta.url)),
      'utf8',
    )
    const colours = language.slice(language.indexOf('export const dlrTokenColors'))
    const print = readFileSync(fileURLToPath(new URL('../print.css', import.meta.url)), 'utf8')
    for (const [token, cls] of Object.entries(DLR_TOKEN_CLASSES)) {
      expect(DLR_TOKENS[token], `${token} maps to no tag`).toBeDefined()
      expect(colours.includes(`'.${cls}'`), `${cls} has no colour in dlrTokenColors`).toBe(true)
      expect(print.includes(`.tk-${token}`), `${token} has no colour on paper`).toBe(true)
    }
  })

  // The other half of it: a view of a script has to actually receive those
  // colours. Both components build their own `EditorView`, so the only thing
  // keeping them in step is the language carrying its own theme.
  it('ships those colours with the language, so every view of a script has them', () => {
    for (const component of ['ScriptEditor.vue', 'ScriptViewer.vue']) {
      const source = readFileSync(
        fileURLToPath(new URL(`../components/${component}`, import.meta.url)),
        'utf8',
      )
      expect(source.includes('dlrLanguage('), `${component} does not use the language`).toBe(true)
      expect(
        source.includes('.dlr-'),
        `${component} styles token classes itself, which is how the two drifted apart`,
      ).toBe(false)
    }
  })
})
