#!/usr/bin/env python3
"""Level a dealer scenario: measure its natural mix, then compute the keeps.

A scenario usually wants its hand types in some deliberate mix while nature
supplies them in another. Levelling discards some of the common types until the
mix comes out as intended. `docs/leveling-strategy.md` explains the method; this
carries it out.

Two files per scenario. The *stock* one is written by hand, declares its types
in a header, and has a placeholder where the levelling goes. The *levelled* one
is generated from it and should never be edited.

    scripts/level-scenario.py stock.dlr -o leveled.dlr

The stock file needs three things:

    # level-types: hcp12_14, hcp15_17, hcp18_19, hcp20_21, hcp22_24
    # level-target: even                 (or: 30, 30, 20, 10, 10)
    # level-budget: 150                  (deals dealt per deal kept; optional)

    ### BEGIN GENERATED LEVELING ###
    noLeveling = 1
    levelTheDeal = noLeveling
    ### END GENERATED LEVELING ###

    condition ... and levelTheDeal

The stock file says what it means in words rather than in a number: `= 1` on its
own reads as "yes, level this deal" when it means the opposite, and no comment
survives being read quickly. `levelTheDeal = noLeveling` cannot be misread.

It also means the stock file runs and can be measured exactly as it stands,
which is what step one does. `keepTheDeal` is accepted as the verdict's name
too, for anyone who prefers the predicate reading.
"""

import argparse
import hashlib
import math
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

BEGIN = "### BEGIN GENERATED LEVELING ###"
END = "### END GENERATED LEVELING ###"
STAMP = "# Generated by scripts/level-scenario.py"

# The only shape of `roll` the thresholds are valid for: a uniform draw over
# 0..scale-1 on every build of every dealer. See docs/leveling-strategy.md.
ROLL_RE = re.compile(
    r"^\s*roll\s*=\s*\(\s*rnd\s*\(\s*(\d+)\s*\)\s*%\s*(\d+)\s*\+\s*(\d+)\s*\)"
    r"\s*%\s*(\d+)\s*$",
    re.M,
)
ROLL_ASSIGNED_RE = re.compile(r"^\s*roll\s*=.*$", re.M)


def canonical_roll(scale):
    return f"roll = (rnd({scale}) % {scale} + {scale}) % {scale}"


def existing_roll(text_outside_block, path):
    """The scale of a `roll` the scenario already defines, or None.

    A scenario may get `roll` from an include, and generating a second
    definition would be at best noise and at worst a second draw. So an existing
    one is used as it stands — but only if it is the shape the thresholds assume.
    Anything else is refused rather than levelled against a distribution that is
    not what it looks like.
    """
    assignments = ROLL_ASSIGNED_RE.findall(text_outside_block)
    if not assignments:
        return None
    if len(assignments) > 1:
        raise Problem(
            f"{path}: `roll` is assigned {len(assignments)} times outside the generated "
            "block. Leave exactly one."
        )
    line = assignments[0]
    match = ROLL_RE.match(line.strip())
    if not match or len(set(match.groups())) != 1:
        raise Problem(
            f"{path}: `roll` is already defined, but not in the form the keeps assume:\n"
            f"    found     {line.strip()}\n"
            f"    expected  {canonical_roll('N')}\n"
            "       The double modulo is what makes the draw uniform on every build; "
            "without it\n       a locally built dealer returns values outside the bound, "
            "or negative ones."
        )
    return int(match.group(1))

# Measured rates are divided by, so a type seen only a handful of times turns a
# sampling wobble into a visibly wrong mix. This is the one way the method goes
# quietly wrong, so it is an error rather than a warning.
MIN_COUNT_PER_TYPE = 500


class Problem(Exception):
    """Something the caller has to fix, reported without a traceback."""


def header_value(text, key):
    """Read a `# key: value` line, the convention the corpus already uses."""
    match = re.search(rf"^#\s*{re.escape(key)}\s*:\s*(.+?)\s*$", text, re.M)
    return match.group(1) if match else None


def parse_stock(path):
    text = path.read_text()
    if STAMP in text:
        raise Problem(
            f"{path} was generated by this tool, not written by hand.\n"
            "       Levelling it again would measure the already-levelled mix and "
            "compute keeps of\n       roughly 1, quietly producing a scenario with no "
            "levelling at all. Use the stock file."
        )
    types = header_value(text, "level-types")
    if not types:
        raise Problem(f"{path}: no `# level-types:` header, so there is nothing to level")
    types = [t.strip() for t in types.split(",") if t.strip()]
    if len(types) < 2:
        raise Problem(f"{path}: `# level-types:` needs at least two types, got {types}")

    target = header_value(text, "level-target") or "even"
    if target.lower() == "even":
        weights = [1.0] * len(types)
    else:
        weights = [float(w) for w in target.split(",")]
        if len(weights) != len(types):
            raise Problem(
                f"{path}: `# level-target:` has {len(weights)} weights for {len(types)} types"
            )
        if min(weights) < 0:
            raise Problem(f"{path}: `# level-target:` weights cannot be negative")
    total = sum(weights)
    if total <= 0:
        raise Problem(f"{path}: `# level-target:` weights sum to zero")
    target = [w / total for w in weights]

    budget = header_value(text, "level-budget")
    budget = float(budget) if budget else None

    if BEGIN not in text or END not in text:
        raise Problem(
            f"{path}: needs a placeholder for the generated levelling:\n"
            f"    {BEGIN}\n    noLeveling = 1\n    levelTheDeal = noLeveling\n    {END}"
        )
    after = text.split(END, 1)[1]
    # The name the scenarios already carry, and the predicate reading for anyone
    # who prefers it. Whichever the stock file uses is what the generated block
    # defines.
    verdict = next((n for n in ("levelTheDeal", "keepTheDeal") if n in after), None)
    if verdict is None:
        raise Problem(
            f"{path}: nothing after the generated block uses `levelTheDeal`, so the "
            "levelling would have no effect. Add it to the condition."
        )

    head, rest = text.split(BEGIN, 1)
    outside = head + rest.split(END, 1)[1]
    roll_scale = existing_roll(outside, path)

    return text, types, target, budget, verdict, roll_scale


def measure(dealer, stock_text, types, deals, seed):
    """Run the stock scenario and report how often each type comes up.

    The measuring averages are appended rather than replacing the scenario's own
    `action`, since dealer accumulates them — so nothing has to parse the
    script's action block to take it apart.
    """
    labels = {t: f"__level__{i}" for i, t in enumerate(types)}
    probe = stock_text + "\n\naction " + ",\n       ".join(
        f'average "{labels[t]}" {t}' for t in types
    ) + "\n"

    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "measure.dlr"
        path.write_text(probe)
        result = subprocess.run(
            [dealer, "-q", "--stats-json", "-p", str(deals), "-s", str(seed), str(path)],
            capture_output=True,
            text=True,
        )
    if result.returncode != 0:
        raise Problem(f"dealer failed while measuring:\n{result.stderr.strip()}")
    try:
        stats = json.loads(result.stdout)
    except json.JSONDecodeError as e:
        raise Problem(f"dealer did not return JSON: {e}\n{result.stdout[:400]}") from e

    by_label = {a["label"]: a for a in stats["averages"]}
    rates, counts = {}, {}
    for t in types:
        entry = by_label.get(labels[t])
        if entry is None:
            raise Problem(f"`{t}` produced no average; is it a variable in the scenario?")
        rates[t] = entry["value"]
        counts[t] = round(entry["value"] * entry["count"])

    if stats["produced"] == 0:
        raise Problem("the scenario produced no deals, so there is nothing to measure")
    thin = [f"{t} seen {counts[t]} times" for t in types if counts[t] < MIN_COUNT_PER_TYPE]
    if thin:
        raise Problem(
            "measured on too few deals to divide by: "
            + "; ".join(thin)
            + f"\n       Raise --deals above {deals}, or widen the rare types."
        )
    covered = sum(rates.values())
    if covered < 0.99:
        raise Problem(
            f"the types cover only {100 * covered:.1f}% of produced deals. They have to "
            "partition them, or the keeps will not add up."
        )
    if covered > 1.01:
        raise Problem(
            f"the types cover {100 * covered:.1f}% of produced deals, so they overlap. "
            "At most one may match any deal."
        )
    return rates, counts, stats


def relax(p, target, budget_acceptance):
    """How much levelling the budget affords, and the mix that results.

    Moving each type a fraction L of the way from its natural rate toward the
    target costs exactly

        acceptance(L) = 1 / (1 + L * (r_max - 1)),  r_max = max(target_j / p_j)

    because the worst ratio is affine in L. So the fraction affordable within a
    budget has a closed form, and there is nothing to search for.

    Relaxing this way pulls every type back toward nature together, rather than
    singling out the rarest — which is the one whose representation the whole
    exercise is usually trying to raise.
    """
    r_max = max(t / p[k] for k, t in target.items())
    if r_max <= 1:
        return 1.0, dict(target), 1.0
    if budget_acceptance is None:
        return 1.0, dict(target), 1 / r_max
    lam = (1 / budget_acceptance - 1) / (r_max - 1)
    lam = max(0.0, min(1.0, lam))
    mix = {k: (1 - lam) * p[k] + lam * target[k] for k in p}
    return lam, mix, 1 / (1 + lam * (r_max - 1))


def measurement_precision(p, mix, deals_measured):
    """How well the keeps are pinned down, and what that costs the mix.

    The verification run and this one answer different questions and want
    different sizes. Verification samples bands at their *target* share, so its
    precision follows from that share alone. This run samples them at their
    *natural* share, and the keep is `p_min / p`, so a relative error in a
    measured rate passes straight through into the mix. The rarest band is
    measured on the fewest deals and therefore sets the answer.
    """
    rarest = min(p, key=p.get)
    rate = p[rarest]
    seen = rate * deals_measured
    if seen <= 0:
        return rarest, 0, float("inf"), float("inf")
    relative = math.sqrt(rate * (1 - rate) / deals_measured) / rate
    return rarest, round(seen), relative, 100 * mix[rarest] * relative


def deals_for_precision(rate, relative):
    """Deals to measure a band of this rate to a given relative precision."""
    return (1 - rate) / (rate * relative * relative)


def thresholds(p, mix, scale=1000):
    """Keep rates as integer thresholds out of `scale`, largest pinned at 1."""
    ratios = {k: mix[k] / p[k] for k in p}
    top = max(ratios.values())
    return {k: min(scale, max(1, round(scale * r / top))) for k, r in ratios.items()}


def render(
    stock_text,
    types,
    keeps,
    p,
    mix,
    lam,
    acceptance,
    base_rate,
    stats,
    source_hash,
    scale,
    verdict,
    roll_is_external,
):
    width = max(len(t) for t in types)
    lines = [
        BEGIN,
        f"{STAMP}. Do not edit; edit the stock",
        "# scenario and regenerate, or the two will disagree without saying so.",
        "#",
        f"# stock sha256   {source_hash}",
        f"# measured over  {stats['produced']:,} deals, seed {stats['seed']}",
        "#",
        f"# {'type':<{width}}  {'natural':>9} {'target':>9} {'keep':>8}",
    ]
    for t in types:
        lines.append(
            f"# {t:<{width}}  {p[t]:>9.5f} {mix[t]:>9.5f} {keeps[t] / scale:>8.4f}"
        )
    lines += [
        "#",
        f"# exactness      {lam:.3f}"
        + ("  (full)" if lam >= 0.999 else "  (relaxed to fit the budget)"),
        f"# acceptance     {acceptance:.4f} of qualifying deals",
        f"# cost           about {1 / (base_rate * acceptance):,.0f} deals dealt per deal kept",
        f"# precision      keeps set by {min(p, key=p.get)}, the rarest, seen "
        f"{round(min(p.values()) * stats['produced']):,} times"
        f" (+-{100 * measurement_precision(p, mix, stats['produced'])[2]:.1f}%);"
        f" expect the mix within"
        f" +-{measurement_precision(p, mix, stats['produced'])[3]:.2f} points",
        "",
    ]
    if roll_is_external:
        lines.append(f"# `roll` comes from the scenario, drawing over 0..{scale - 1}.")
    else:
        lines.append(canonical_roll(scale))
    lines.append("")
    for t in types:
        keep = keeps[t]
        if keep >= scale:
            lines.append(f"level_{t} = {t}")
        else:
            lines.append(f"level_{t} = {t} and roll < {keep}")
    lines.append(f"{verdict} = " + " or ".join(f"level_{t}" for t in types))
    lines.append(END)

    head, rest = stock_text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + "\n".join(lines) + tail


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("stock", type=Path, help="the hand-written scenario")
    ap.add_argument("-o", "--output", type=Path, help="where to write the levelled scenario")
    ap.add_argument("--dealer", default="dealer", help="the dealer binary to measure with")
    ap.add_argument("--deals", type=int, default=100000, help="deals to measure over")
    ap.add_argument("--seed", type=int, default=1, help="seed for the measuring run")
    ap.add_argument("--budget", type=float, help="deals dealt per deal kept; overrides the header")
    ap.add_argument(
        "--scale",
        type=int,
        help="threshold denominator (default 1000, or whatever an existing `roll` uses)",
    )
    ap.add_argument("--dry-run", action="store_true", help="report the numbers, write nothing")
    args = ap.parse_args()

    stock_text, types, target_list, header_budget, verdict, roll_scale = parse_stock(args.stock)
    target = dict(zip(types, target_list))
    budget = args.budget if args.budget is not None else header_budget

    # A `roll` the scenario already defines sets the denominator, since the
    # thresholds have to be read against the draw that actually happens.
    if roll_scale is not None:
        if args.scale is not None and args.scale != roll_scale:
            raise Problem(
                f"--scale {args.scale} disagrees with the `roll` already in the scenario, "
                f"which draws over 0..{roll_scale - 1}. Drop --scale, or change the scenario."
            )
        scale = roll_scale
    else:
        scale = args.scale if args.scale is not None else 1000

    p, counts, stats = measure(args.dealer, stock_text, types, args.deals, args.seed)
    base_rate = stats["produced"] / stats["generated"]

    # A budget in deals-dealt-per-deal-kept has to become an acceptance rate
    # among the deals that already pass the scenario's own condition.
    budget_acceptance = None
    if budget:
        budget_acceptance = min(1.0, (1 / budget) / base_rate)
    lam, mix, acceptance = relax(p, target, budget_acceptance)
    keeps = thresholds(p, mix, scale)
    cost = 1 / (base_rate * acceptance)

    width = max(len(t) for t in types)
    print(f"measured over {stats['produced']:,} deals of {stats['generated']:,} dealt")
    print(f"  base condition accepts {100 * base_rate:.3f}% of deals\n")
    print(f"  {'type':<{width}}  {'natural':>9} {'target':>9} {'mix':>9} {'keep':>8} {'seen':>9}")
    for t in types:
        print(
            f"  {t:<{width}}  {p[t]:>9.5f} {target[t]:>9.5f} {mix[t]:>9.5f} "
            f"{keeps[t] / scale:>8.4f} {counts[t]:>9,}"
        )
    rarest, seen, relative, mix_error = measurement_precision(p, mix, stats["produced"])
    print(f"\n  exactness {lam:.3f}" + ("" if lam >= 0.999 else "  (relaxed to fit the budget)"))
    print(f"  acceptance {acceptance:.4f} of qualifying deals")
    print(f"  about {cost:,.0f} deals dealt per deal kept")
    print(
        f"\n  keeps pinned down by `{rarest}`, the rarest, seen {seen:,} times:"
        f" +-{100 * relative:.1f}%"
    )
    print(f"  so expect the delivered mix within about +-{mix_error:.2f} points of target")
    tighter = mix_error / 3
    if tighter > 0.05:
        needed = deals_for_precision(p[rarest], relative / 3)
        print(f"  for +-{tighter:.2f} points, measure on --deals {needed:,.0f}")
    if budget and lam < 0.999:
        print(f"  a fully level mix would have cost {1 / (base_rate / max(target[t] / p[t] for t in types)):,.0f}")

    if args.dry_run:
        return 0
    if not args.output:
        raise Problem("no --output given; use --dry-run to see the numbers without writing")

    source_hash = hashlib.sha256(stock_text.encode()).hexdigest()[:16]
    args.output.write_text(
        render(
            stock_text,
            types,
            keeps,
            p,
            mix,
            lam,
            acceptance,
            base_rate,
            stats,
            source_hash,
            scale,
            verdict,
            roll_scale is not None,
        )
    )
    print(f"\nwrote {args.output}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Problem as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(1)
